# Generated by Django 2.2.14 on 2023-04-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20230413_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mode',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
